format = '$time$all'
follow_symlinks = false
add_newline = true 

[username]
style_user = 'white bold'
style_root = 'black bold'
#format = '\[[$user]($style)'
format = '\[[$user](bold 208)'
disabled = false
show_always = true

[hostname]
ssh_only = false
#format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
format = '[$ssh_symbol](bold blue)@[$hostname](bold 109)\]: '
#trim_at = '.companyname.com'
disabled = false

[time]
disabled = false
#format = '🕙[\[ $time \]]($style) '
format = '\[[$time](bold 245)\] '
time_format = '%T'
#utc_time_offset = '-5'
#time_range = '10:00:00-14:00:00'

#[character]
#vimcmd_symbol = '[N](bold green)'

[directory]
truncation_length = 0
truncate_to_repo = false
truncation_symbol = '…/'

[localip]
disabled = true

