#!/bin/sh
HISTFILE="$HOME/.zsh_history"
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='lvim +Man!'
export MANWIDTH=999
export EDITOR=lvim
export PATH=$HOME/.cargo/bin:$PATH
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export ENTE_CLI_SECRETS_PATH=$HOME/.ente/ente_secret.txt
export ENTE_CLI_CONFIG_PATH=$HOME/.config/ente-cli/

