#!/bin/sh
alias f='zi'
which lazygit > /dev/null && alias g='lazygit'
which yazi > /dev/null && alias y='yazi'
alias zshconfig='${EDITOR} ~/.zshrc'

alias vim='nvim'
alias vi='vim'
alias v='vim'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
#alias cp='cp -i'
#alias mv='mv -i'
#alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

alias ls='eza --color=always --group-directories-first --icons'
#alias ll='exa -lgM --git --time-style long-iso'
alias ll='ls -lgM --git --time-style long-iso'
#alias la='exa -lga --color=always --group-directories-first'
alias la='ll -a'

alias ..='cd ..'

# gpg encryption
# verify signature for isos
#alias gpg-check="gpg --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
#alias gpg-retrieve="gpg --keyserver-options auto-key-retrieve --receive-keys"

